services:
  jaeger:
    image: jaegertracing/jaeger:2.4.0
    ports:
      - "16686:16686"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # Health check extension
    volumes:
      - ./otel-collector-config.yaml:/otel-collector-config.yaml:ro
    command: [ "--config=/otel-collector-config.yaml" ]
    restart: unless-stopped
    depends_on:
      - jaeger
