healthcheck:
  workingText: "WORKING"
mqttserver:
  host: localhost
  port: 1883
  user: mqttclient
  pass: password
  usetls: false
  insecure_tls: true
newrelic:
  key: ""
sentry:
  url: ""
jaeger:
  disabled: true
  samplingProbability: 0.001
dogstatsd:
  host: localhost:8125
  prefix: arkadiko.
  tags_prefix: ""
  rate: 1
httpserver:
  url: "http://localhost:8081"
  user: admin
  pass: public
  metricsPort: 9090
