healthcheck:
  workingText: "WORKING"
mqttserver:
  host: localhost
  port: 1883
  user: mqttclient
  pass: password
  usetls: false
  insecure_tls: true
  timeout: 500ms
newrelic:
  key: ""
sentry:
  url: ""
otel:
  collector:
    host: localhost
    port: "4317"
  service:
    name: arkadiko
  disabled: false
  samplingProbability: 0.1
dogstatsd:
  host: localhost:8125
  prefix: arkadiko.
  tags_prefix: ""
  rate: 1
httpserver:
  url: "http://localhost:8081"
  user: admin
  pass: public
  metricsPort: 9090
