name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.15'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download dependencies
        run: go mod download
      - name: Run tests
        run: make test-ci
      - name: Install goveralls
        env:
          GO111MODULE: off
        run: go get github.com/mattn/goveralls
      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: go run github.com/mattn/goveralls -coverprofile coverage-all.out -service=github
